-- 005_seed_questions.sql
-- Seed de 15 questões genéricas para testes imediatos de simulado.
-- topic_id 1 (assume-se que seja Português/Gerais)
-- topic_id 2 (assume-se que seja TI/Específicos)

INSERT INTO questions (topic_id, statement, alt_a, alt_b, alt_c, alt_d, alt_e, correct_answer, explanation, source, banca, year, orgao) VALUES
(1, 'Assinale a alternativa em que a crase foi empregada corretamente:', 'Fui a pé.', 'Dirigiu-se à ela.', 'Refiro-me àquilo.', 'Ficou cara a cara.', 'Vendeu à prazo.', 'C', 'Apenas em "àquilo" ocorre a fusão da preposição "a" com o pronome demonstrativo.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(1, 'Na frase "Os alunos cujos pais faltaram...", o pronome relativo exerce a função de:', 'Sujeito', 'Objeto direto', 'Adjunto adnominal', 'Complemento nominal', 'Predicativo', 'C', '"cujos" indica posse e funciona sempre como adjunto adnominal.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(1, 'Qual a classificação morfológica da palavra destacada em "Fala SÉRIO"?', 'Substantivo', 'Adjetivo', 'Advérbio', 'Pronome', 'Conjunção', 'C', 'Neste contexto, "sério" atua modificando o verbo falar, portanto é advérbio.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(1, 'Indique a frase com erro de concordância verbal:', 'Fazem cinco anos que não o vejo.', 'Havia muitos problemas na empresa.', 'Devem existir outras opções.', 'Fui eu quem fez o trabalho.', 'Choveu granizo ontem.', 'A', 'O verbo "fazer" indicando tempo decorrido é impessoal (faz cinco anos).', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(1, 'Sobre os gêneros textuais, um edital de concurso público classifica-se predominantemente como texto:', 'Narrativo', 'Descritivo', 'Informativo e prescritivo', 'Argumentativo', 'Poético', 'C', 'O edital informa regras e prescreve condutas para a realização do certame.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'No modelo OSI, o protocolo IP opera em qual camada?', 'Física', 'Enlace', 'Rede', 'Transporte', 'Aplicação', 'C', 'O IP é o principal protocolo da camada de Rede no modelo OSI e TCP/IP.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'O que caracteriza a computação em nuvem no modelo IaaS?', 'Fornecimento de software pronto.', 'Fornecimento de infraestrutura como servidores e armazenamento.', 'Fornecimento de plataforma de desenvolvimento.', 'Fornecimento de processos de negócio.', 'Fornecimento apenas de banco de dados.', 'B', 'IaaS (Infrastructure as a Service) entrega infra de hardware virtualizada.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'Qual destas estruturas de dados segue o princípio LIFO?', 'Fila', 'Pilha', 'Árvore', 'Grafo', 'Lista Encadeada', 'B', 'Pilha (Stack) usa LIFO: Last In, First Out.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'O protocolo SNMP utiliza por padrão qual protocolo de transporte e porta?', 'TCP 161', 'UDP 161', 'TCP 80', 'UDP 53', 'TCP 443', 'B', 'SNMP usa UDP nas portas 161 (agente) e 162 (trap).', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'Qual a principal vantagem de índices em bancos de dados relacionais?', 'Reduzir espaço em disco.', 'Acelerar operações de escrita (INSERT).', 'Acelerar consultas (SELECT).', 'Garantir integridade referencial.', 'Criptografar dados sensíveis.', 'C', 'Índices permitem buscas muito mais rápidas sacrificando um pouco a velocidade de inserção/atualização.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'No PMBOK, a estrutura analítica do projeto (EAP) é um artefato de qual área de conhecimento?', 'Integração', 'Escopo', 'Cronograma', 'Riscos', 'Qualidade', 'B', 'A EAP decompoe o Escopo do projeto em pacotes de trabalho.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'O que é injeção de dependência em arquitetura de software?', 'Uma falha de segurança (SQL Injection).', 'Um padrão de projeto para desacoplar a criação de objetos.', 'Uma forma de forçar herança múltipla.', 'O ato de baixar bibliotecas via NPM.', 'Um recurso do banco de dados.', 'B', 'Padrão que permite injetar implementações concretas em interfaces, diminuindo o acoplamento.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'Na metodologia Scrum, o que define a meta de uma Sprint?', 'O Scrum Master', 'A Daily Scrum', 'O Sprint Goal (Meta da Sprint)', 'O Burndown Chart', 'O Product Owner isoladamente', 'C', 'O Sprint Goal é um objetivo único estabelecido durante a Sprint Planning.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'Sobre REST e APIs, qual código HTTP indica sucesso na criação de um novo recurso?', '200 OK', '201 Created', '204 No Content', '400 Bad Request', '500 Internal Server Error', 'B', '201 Created é o código semântico correto para recursos recém-criados via POST.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA'),
(2, 'Em segurança da informação, a confidencialidade garante que:', 'A informação esteja sempre disponível.', 'A informação não foi alterada.', 'A informação seja acessível apenas por pessoas autorizadas.', 'O remetente não possa negar a autoria.', 'O sistema tenha cópias de segurança.', 'C', 'Confidencialidade visa proteger dados contra acessos não autorizados.', 'exemplo - substituir por questões reais', 'Cebraspe', 2026, 'TCE-MA');
